"""empty message

Revision ID: 02abcbf45dca
Revises: 10bdc03a02d6
Create Date: 2025-03-26 14:57:31.954698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02abcbf45dca'
down_revision = '10bdc03a02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderdetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderdetails_amt', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderdetails', schema=None) as batch_op:
        batch_op.drop_column('orderdetails_amt')

    # ### end Alembic commands ###
